### ISSUE TITLE
Feature Request: Consistency in generated webfont character IDs.

### ISSUE THREAD

**Issue by phyllisstein** [Templarian/MaterialDesign#253]
Hey there! I hate to be a nudzh, especially w/r/t a project of which I'm so completely enamored---seriously, thank you for all your hard work, it's a thing of absolute beauty---but I was wondering if there was any way to adjust the webfont build process so that the character IDs stayed more or less consistent across builds.

It's probably a bit of an edge case (though hopefully not an _extreme_ edge case), but in at least one project with which I'm using the webfont, I have CSS that looks like this:

```css
.members-banner__member--featured::after {
  bottom: 0;
  color: #ffeb3b;
  content: '\f431';
  font-family: 'MaterialDesignIcons';
  font-size: 0.791em;
  pointer-events: none;
  position: absolute;
  right: 0;
}
```

As of MDI 0.9.72-alpha, that added a pretty little star to any element that got the class. But every time the build changes, I have to go back and make sure it's still a pretty little star, rather than a pretty little cloud or (my personal favorite) pretty little Clippy. Is there any way to, say, have the build task sort the SVGs by date added, rather than by alphabetizing them?

Thanks in advance for considering it! And best of luck with your continued development.
