### ISSUE TITLE
Aliases for battery and battery-outline

### ISSUE THREAD

**Issue by gnaeser** [Templarian/MaterialDesign#2926]
It would make coding easier should battery have an alias battery-100, and battery-outline have an alias battery-0. (Fewer special cases needed if level is returned/set to 0..100 in steps of 10.)

**Comment by Templarian** [comment]
This was discussed internally as a breaking change for this next release. We do not do aliases outside of searching. It would have to be a rename.

The solution for now would be to add it in your sass/css.

```scss
.battery-0 {
    content: mdi('battery-outline');
}
```

```css
.battery-0 {
    content: '\f08e';
}
```
