### ISSUE TITLE
No Cache TTL specified

### ISSUE THREAD

**Issue by Berkmann18** [Templarian/MaterialDesign#5124]
I've been trying to get a site to use a single icon and did this using the `@font-face` approach with `src` pointing to URLs like https://cdn.materialdesignicons.com/5.0.45/fonts/materialdesignicons-webfont.woff2?v=5.0.45.
The problem is that LightHouse shows that there's no Cache Time To Live info specified which ends up affecting the performance, as the browser has to pull the exact same copy of the 270KB+ of web fonts (which could be cached).

**Comment by Templarian** [comment]
@Berkmann18 What browser are you seeing it redownload the font in? Make sure you don't have your dev tools configured to clear cache.

I just checked latest Chrome/FF and it's working as expected.

**Comment by Berkmann18** [comment]
@Templarian Chromium I believe (I'm seeing this on a Lighthouse CI):
![image](https://user-images.githubusercontent.com/8260834/80763036-8e96da80-8b35-11ea-902a-bbf6c153c6fc.png)

**Comment by Templarian** [comment]
If you're only using 1 icon definitely use SVG by the way. Actually you should never use the webfont, but that's another issue. 😄 

I think this is a bug, there use to be a cache header coming from my CDN provider that gets appended when it mirrors the content.

@Berkmann18 Good find. Not sure what changed, but we'll get this fixed. It should basically cache forever as those assets are completely static and never change.

**Comment by Templarian** [comment]
This is a good thing last time I checked we were reaching 30TB a month. So hopefully this can help reduce that (we're capped at 40TB).

**Comment by Berkmann18** [comment]
@Templarian 
> If you're only using 1 icon definitely use SVG by the way. Actually you should never use the webfont, but that's another issue.

I was considering this, but I'm unsure how to easily programmatically (and dynamically) change its colour.
I was hoping in reducing the URLs called, but the standard MD stylesheet is bigger and I noticed having:
```css
@font-face {
  font-family: "Material Design Icons";
  src: url("https://cdn.materialdesignicons.com/5.0.45/fonts/materialdesignicons-webfont.eot?v=5.0.45");
  src:
    url("https://cdn.materialdesignicons.com/5.0.45/fonts/materialdesignicons-webfont.woff2?v=5.0.45")
    format("woff2"),
    url("https://cdn.materialdesignicons.com/5.0.45/fonts/materialdesignicons-webfont.ttf?v=5.0.45")
    format("truetype");
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}

.mdi::before {
  display: inline-block;
  font: normal normal normal 24px/1 "Material Design Icons", sans-serif;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.mdi-hand-right::before {
  content: "\F0E47";
}
```
... would impact the startup performance less.
I guess I need to look deeper in how I can change that SVG from black<->red in JS and see if that works.

Good to know, it should have a long TTL.

> This is a good thing last time I checked we were reaching 30TB a month. So hopefully this can help reduce that (we're capped at 40TB).

That definitely should.
