### ISSUE TITLE
is there an attribute or class for resizing an icon?

### ISSUE THREAD

**Issue by beebase** [Templarian/MaterialDesign#590]
...or do you need create your own classes in a separate .css file?

**Comment by Templarian** [comment]
Do you mean like font awesome has the `fa-lg`, `fa-2x`, `fa-3x`, `fa-4x`, and `fa-5x`?

I've been thinking of adding them, seems like it may be useful.

**Comment by beebase** [comment]
Yes.
I added a custom css based on 
http://google.github.io/material-design-icons/
```css
.mdi-18px { font-size: 18px; }
.mdi-24px { font-size: 24px; }
.mdi-36px { font-size: 36px; }
.mdi-48px { font-size: 48px; }
.mdi-dark { color: rgba(0, 0, 0, 0.54); }
.mdi-dark.mdi-inactive { color: rgba(0, 0, 0, 0.26); }
.mdi-light { color: rgba(255, 255, 255, 1); }
.mdi-light.mdi-inactive { color: rgba(255, 255, 255, 0.3); }
```

works pretty well with  angular material.
(the default icon size was a bit too small)
```html
 <md-button class="md-fab md-mini mdi mdi-pencil-box-outline mdi-24px"
                    ng-click="show()">
 </md-button>
```

![image](https://cloud.githubusercontent.com/assets/446089/9157067/86e08ab2-3eef-11e5-9fb8-7f5a0a033c03.png)
