### ISSUE TITLE
Add Unicode and Font-Family to the Icon's Export Modal

### ISSUE THREAD

**Issue by jetrotal** [Templarian/MaterialDesign#6115]
I'm testing some CSS coding on CodePen:

```CSS
@import url("https://cdn.jsdelivr.net/npm/@mdi/font@5.9.55/css/materialdesignicons.min.css");

.DragItem > .header::before {
  content: "\F01DB";
  font-family: "Material Design Icons";
}

```
To get the Icon's Unicode, i had to open `materialdesignicons.min.css` and search for `"mdi-drag"`.

I wish I could reduce this extra step when testing icons like this.

A suggestion i have for this is to add a JS comment under the react code snippet that we have on the Export Modal,
something like this:
![image](https://user-images.githubusercontent.com/45118493/129179629-ecfd471b-60a4-41cf-88ee-e4b8951206cf.png)

It doesn't have to be ` // this is "\f01db" from font-family:"material design icons"; ` 
anything containing an easy to copy unicode + font-family values would give us a huge help to set up this kind of Icon usage.

Thanks in Advance!
