### ISSUE TITLE
Idea for RTL Icons

### ISSUE THREAD

**Issue by Hawmex** [Templarian/MaterialDesign#6150]
### What is your question?

I think a neat way to use bidirectional icons in the web would be using [CSS `:dir()` pseudo-class](https://www.chromestatus.com/feature/5751531651465216) (Maybe instead of `*-rtl` or besides it).

### Example:

```css
.my-arrow-icon::before {
  content: /* LTR Variant */;
}

.my-arrow-icon:dir(rtl)::before {
  content: /* RTL Variant */;
}
```

I prefer this approach because the dev won't have to worry about changing icon class names when direction is changed.
The whole web/CSS ecosystem has moved towards bidirectionality by default; for example `flexbox`, `grid`, `margin-inline`, `padding-inline`, etc. all use the `start` and `end` terms instead of `left` and `right` and devs don't have to worry about direction change in these cases.
